[package]
name = "RustHttpServer_v2"
version = "0.1.4"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
serde_json = "1.0.143"
bytes = "1.10.1"
httparse = "1.10.1"
percent-encoding = "2.3.2"
sanitize-filename = "0.6.0"
cookie = "0.18.1"

